/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCloseRouteImport } from './routes/_app.close'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppPortfolioIndexRouteImport } from './routes/_app.portfolio.index'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/_app.reports.trial-balance'
import { Route as AppReportsIncomeStatementRouteImport } from './routes/_app.reports.income-statement'
import { Route as AppReportsGeneralLedgerRouteImport } from './routes/_app.reports.general-ledger'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/_app.reports.balance-sheet'
import { Route as AppReportsAuditPackRouteImport } from './routes/_app.reports.audit-pack'
import { Route as AppHelpSlugRouteImport } from './routes/_app.help.$slug'
import { Route as AppGovernanceViolationsRouteImport } from './routes/_app.governance.violations'
import { Route as AppGovernanceTransitionsRouteImport } from './routes/_app.governance.transitions'
import { Route as AppGovernanceMeetingsRouteImport } from './routes/_app.governance.meetings'
import { Route as AppGovernanceHomeownersRouteImport } from './routes/_app.governance.homeowners'
import { Route as AppGovernanceArchRequestsRouteImport } from './routes/_app.governance.arch-requests'
import { Route as AppFinanceReservesRouteImport } from './routes/_app.finance.reserves'
import { Route as AppFinanceJournalRouteImport } from './routes/_app.finance.journal'
import { Route as AppFinanceDuesRouteImport } from './routes/_app.finance.dues'
import { Route as AppFinanceAccountsRouteImport } from './routes/_app.finance.accounts'
import { Route as AppBankStatementsRouteImport } from './routes/_app.bank.statements'
import { Route as AppBankReconcileRouteImport } from './routes/_app.bank.reconcile'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCloseRoute = AppCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioIndexRoute = AppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AppRoute,
} as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIncomeStatementRoute =
  AppReportsIncomeStatementRouteImport.update({
    id: '/reports/income-statement',
    path: '/reports/income-statement',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsGeneralLedgerRoute = AppReportsGeneralLedgerRouteImport.update({
  id: '/reports/general-ledger',
  path: '/reports/general-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAuditPackRoute = AppReportsAuditPackRouteImport.update({
  id: '/reports/audit-pack',
  path: '/reports/audit-pack',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpSlugRoute = AppHelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppHelpRoute,
} as any)
const AppGovernanceViolationsRoute = AppGovernanceViolationsRouteImport.update({
  id: '/governance/violations',
  path: '/governance/violations',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceTransitionsRoute =
  AppGovernanceTransitionsRouteImport.update({
    id: '/governance/transitions',
    path: '/governance/transitions',
    getParentRoute: () => AppRoute,
  } as any)
const AppGovernanceMeetingsRoute = AppGovernanceMeetingsRouteImport.update({
  id: '/governance/meetings',
  path: '/governance/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceHomeownersRoute = AppGovernanceHomeownersRouteImport.update({
  id: '/governance/homeowners',
  path: '/governance/homeowners',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceArchRequestsRoute =
  AppGovernanceArchRequestsRouteImport.update({
    id: '/governance/arch-requests',
    path: '/governance/arch-requests',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceReservesRoute = AppFinanceReservesRouteImport.update({
  id: '/finance/reserves',
  path: '/finance/reserves',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceJournalRoute = AppFinanceJournalRouteImport.update({
  id: '/finance/journal',
  path: '/finance/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceDuesRoute = AppFinanceDuesRouteImport.update({
  id: '/finance/dues',
  path: '/finance/dues',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceAccountsRoute = AppFinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBankStatementsRoute = AppBankStatementsRouteImport.update({
  id: '/bank/statements',
  path: '/bank/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppBankReconcileRoute = AppBankReconcileRouteImport.update({
  id: '/bank/reconcile',
  path: '/bank/reconcile',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/close': typeof AppCloseRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/owner/': typeof OwnerIndexRoute
  '/bank/reconcile': typeof AppBankReconcileRoute
  '/bank/statements': typeof AppBankStatementsRoute
  '/finance/accounts': typeof AppFinanceAccountsRoute
  '/finance/dues': typeof AppFinanceDuesRoute
  '/finance/journal': typeof AppFinanceJournalRoute
  '/finance/reserves': typeof AppFinanceReservesRoute
  '/governance/arch-requests': typeof AppGovernanceArchRequestsRoute
  '/governance/homeowners': typeof AppGovernanceHomeownersRoute
  '/governance/meetings': typeof AppGovernanceMeetingsRoute
  '/governance/transitions': typeof AppGovernanceTransitionsRoute
  '/governance/violations': typeof AppGovernanceViolationsRoute
  '/help/$slug': typeof AppHelpSlugRoute
  '/reports/audit-pack': typeof AppReportsAuditPackRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/reports/income-statement': typeof AppReportsIncomeStatementRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/portfolio/': typeof AppPortfolioIndexRoute
  '/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/close': typeof AppCloseRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/owner': typeof OwnerIndexRoute
  '/bank/reconcile': typeof AppBankReconcileRoute
  '/bank/statements': typeof AppBankStatementsRoute
  '/finance/accounts': typeof AppFinanceAccountsRoute
  '/finance/dues': typeof AppFinanceDuesRoute
  '/finance/journal': typeof AppFinanceJournalRoute
  '/finance/reserves': typeof AppFinanceReservesRoute
  '/governance/arch-requests': typeof AppGovernanceArchRequestsRoute
  '/governance/homeowners': typeof AppGovernanceHomeownersRoute
  '/governance/meetings': typeof AppGovernanceMeetingsRoute
  '/governance/transitions': typeof AppGovernanceTransitionsRoute
  '/governance/violations': typeof AppGovernanceViolationsRoute
  '/help/$slug': typeof AppHelpSlugRoute
  '/reports/audit-pack': typeof AppReportsAuditPackRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/reports/income-statement': typeof AppReportsIncomeStatementRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/portfolio': typeof AppPortfolioIndexRoute
  '/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/close': typeof AppCloseRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/owner/': typeof OwnerIndexRoute
  '/_app/bank/reconcile': typeof AppBankReconcileRoute
  '/_app/bank/statements': typeof AppBankStatementsRoute
  '/_app/finance/accounts': typeof AppFinanceAccountsRoute
  '/_app/finance/dues': typeof AppFinanceDuesRoute
  '/_app/finance/journal': typeof AppFinanceJournalRoute
  '/_app/finance/reserves': typeof AppFinanceReservesRoute
  '/_app/governance/arch-requests': typeof AppGovernanceArchRequestsRoute
  '/_app/governance/homeowners': typeof AppGovernanceHomeownersRoute
  '/_app/governance/meetings': typeof AppGovernanceMeetingsRoute
  '/_app/governance/transitions': typeof AppGovernanceTransitionsRoute
  '/_app/governance/violations': typeof AppGovernanceViolationsRoute
  '/_app/help/$slug': typeof AppHelpSlugRoute
  '/_app/reports/audit-pack': typeof AppReportsAuditPackRoute
  '/_app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/_app/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/_app/reports/income-statement': typeof AppReportsIncomeStatementRoute
  '/_app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/_app/portfolio/': typeof AppPortfolioIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/portal'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/billing'
    | '/close'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/owner/'
    | '/bank/reconcile'
    | '/bank/statements'
    | '/finance/accounts'
    | '/finance/dues'
    | '/finance/journal'
    | '/finance/reserves'
    | '/governance/arch-requests'
    | '/governance/homeowners'
    | '/governance/meetings'
    | '/governance/transitions'
    | '/governance/violations'
    | '/help/$slug'
    | '/reports/audit-pack'
    | '/reports/balance-sheet'
    | '/reports/general-ledger'
    | '/reports/income-statement'
    | '/reports/trial-balance'
    | '/invitations/$token/accept'
    | '/portfolio/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/billing'
    | '/close'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/owner'
    | '/bank/reconcile'
    | '/bank/statements'
    | '/finance/accounts'
    | '/finance/dues'
    | '/finance/journal'
    | '/finance/reserves'
    | '/governance/arch-requests'
    | '/governance/homeowners'
    | '/governance/meetings'
    | '/governance/transitions'
    | '/governance/violations'
    | '/help/$slug'
    | '/reports/audit-pack'
    | '/reports/balance-sheet'
    | '/reports/general-ledger'
    | '/reports/income-statement'
    | '/reports/trial-balance'
    | '/invitations/$token/accept'
    | '/portfolio'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/portal'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/_app/billing'
    | '/_app/close'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/settings'
    | '/owner/'
    | '/_app/bank/reconcile'
    | '/_app/bank/statements'
    | '/_app/finance/accounts'
    | '/_app/finance/dues'
    | '/_app/finance/journal'
    | '/_app/finance/reserves'
    | '/_app/governance/arch-requests'
    | '/_app/governance/homeowners'
    | '/_app/governance/meetings'
    | '/_app/governance/transitions'
    | '/_app/governance/violations'
    | '/_app/help/$slug'
    | '/_app/reports/audit-pack'
    | '/_app/reports/balance-sheet'
    | '/_app/reports/general-ledger'
    | '/_app/reports/income-statement'
    | '/_app/reports/trial-balance'
    | '/invitations/$token/accept'
    | '/_app/portfolio/'
    | '/_app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/close': {
      id: '/_app/close'
      path: '/close'
      fullPath: '/close'
      preLoaderRoute: typeof AppCloseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio/': {
      id: '/_app/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AppPortfolioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports/trial-balance': {
      id: '/_app/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/income-statement': {
      id: '/_app/reports/income-statement'
      path: '/reports/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof AppReportsIncomeStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/general-ledger': {
      id: '/_app/reports/general-ledger'
      path: '/reports/general-ledger'
      fullPath: '/reports/general-ledger'
      preLoaderRoute: typeof AppReportsGeneralLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/balance-sheet': {
      id: '/_app/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/audit-pack': {
      id: '/_app/reports/audit-pack'
      path: '/reports/audit-pack'
      fullPath: '/reports/audit-pack'
      preLoaderRoute: typeof AppReportsAuditPackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/$slug': {
      id: '/_app/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof AppHelpSlugRouteImport
      parentRoute: typeof AppHelpRoute
    }
    '/_app/governance/violations': {
      id: '/_app/governance/violations'
      path: '/governance/violations'
      fullPath: '/governance/violations'
      preLoaderRoute: typeof AppGovernanceViolationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance/transitions': {
      id: '/_app/governance/transitions'
      path: '/governance/transitions'
      fullPath: '/governance/transitions'
      preLoaderRoute: typeof AppGovernanceTransitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance/meetings': {
      id: '/_app/governance/meetings'
      path: '/governance/meetings'
      fullPath: '/governance/meetings'
      preLoaderRoute: typeof AppGovernanceMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance/homeowners': {
      id: '/_app/governance/homeowners'
      path: '/governance/homeowners'
      fullPath: '/governance/homeowners'
      preLoaderRoute: typeof AppGovernanceHomeownersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance/arch-requests': {
      id: '/_app/governance/arch-requests'
      path: '/governance/arch-requests'
      fullPath: '/governance/arch-requests'
      preLoaderRoute: typeof AppGovernanceArchRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/reserves': {
      id: '/_app/finance/reserves'
      path: '/finance/reserves'
      fullPath: '/finance/reserves'
      preLoaderRoute: typeof AppFinanceReservesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/journal': {
      id: '/_app/finance/journal'
      path: '/finance/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof AppFinanceJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/dues': {
      id: '/_app/finance/dues'
      path: '/finance/dues'
      fullPath: '/finance/dues'
      preLoaderRoute: typeof AppFinanceDuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/accounts': {
      id: '/_app/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof AppFinanceAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/statements': {
      id: '/_app/bank/statements'
      path: '/bank/statements'
      fullPath: '/bank/statements'
      preLoaderRoute: typeof AppBankStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/reconcile': {
      id: '/_app/bank/reconcile'
      path: '/bank/reconcile'
      fullPath: '/bank/reconcile'
      preLoaderRoute: typeof AppBankReconcileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHelpRouteChildren {
  AppHelpSlugRoute: typeof AppHelpSlugRoute
}

const AppHelpRouteChildren: AppHelpRouteChildren = {
  AppHelpSlugRoute: AppHelpSlugRoute,
}

const AppHelpRouteWithChildren =
  AppHelpRoute._addFileChildren(AppHelpRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCloseRoute: typeof AppCloseRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppBankReconcileRoute: typeof AppBankReconcileRoute
  AppBankStatementsRoute: typeof AppBankStatementsRoute
  AppFinanceAccountsRoute: typeof AppFinanceAccountsRoute
  AppFinanceDuesRoute: typeof AppFinanceDuesRoute
  AppFinanceJournalRoute: typeof AppFinanceJournalRoute
  AppFinanceReservesRoute: typeof AppFinanceReservesRoute
  AppGovernanceArchRequestsRoute: typeof AppGovernanceArchRequestsRoute
  AppGovernanceHomeownersRoute: typeof AppGovernanceHomeownersRoute
  AppGovernanceMeetingsRoute: typeof AppGovernanceMeetingsRoute
  AppGovernanceTransitionsRoute: typeof AppGovernanceTransitionsRoute
  AppGovernanceViolationsRoute: typeof AppGovernanceViolationsRoute
  AppReportsAuditPackRoute: typeof AppReportsAuditPackRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsGeneralLedgerRoute: typeof AppReportsGeneralLedgerRoute
  AppReportsIncomeStatementRoute: typeof AppReportsIncomeStatementRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
  AppPortfolioIndexRoute: typeof AppPortfolioIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCloseRoute: AppCloseRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppBankReconcileRoute: AppBankReconcileRoute,
  AppBankStatementsRoute: AppBankStatementsRoute,
  AppFinanceAccountsRoute: AppFinanceAccountsRoute,
  AppFinanceDuesRoute: AppFinanceDuesRoute,
  AppFinanceJournalRoute: AppFinanceJournalRoute,
  AppFinanceReservesRoute: AppFinanceReservesRoute,
  AppGovernanceArchRequestsRoute: AppGovernanceArchRequestsRoute,
  AppGovernanceHomeownersRoute: AppGovernanceHomeownersRoute,
  AppGovernanceMeetingsRoute: AppGovernanceMeetingsRoute,
  AppGovernanceTransitionsRoute: AppGovernanceTransitionsRoute,
  AppGovernanceViolationsRoute: AppGovernanceViolationsRoute,
  AppReportsAuditPackRoute: AppReportsAuditPackRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsGeneralLedgerRoute: AppReportsGeneralLedgerRoute,
  AppReportsIncomeStatementRoute: AppReportsIncomeStatementRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
  AppPortfolioIndexRoute: AppPortfolioIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OwnerRouteChildren {
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
