/**
 * Collects the repository statistics quoted in README.md and portfolio/METRICS.md.
 *
 * Every number in the README is generated by this module so a reader who
 * doubts one can regenerate it, and so claims cannot silently go stale — the
 * `verify` chain runs this in check mode.
 *
 * All I/O is injected so the logic is testable without a git repository.
 */

/** Source extensions counted toward the lines-of-code figure. */
export const SOURCE_EXTENSIONS = ["ts", "tsx", "astro", "sql", "css"] as const;

/** Workspaces whose vitest config must declare the coverage thresholds. */
export const COVERED_WORKSPACES = [
  "apps/api",
  "apps/app",
  "apps/web",
  "packages/shared",
  "scripts",
] as const;

export interface MetricsDeps {
  /** Run a command and return stdout. Throws on non-zero exit. */
  run: (command: string, args: readonly string[]) => string;
  /** Read a UTF-8 file. Returns null when it does not exist. */
  readFile: (relativePath: string) => string | null;
  /** Resolve the number of unique HTTP endpoints registered on the API. */
  countEndpoints: () => Promise<number>;
}

export interface LocMetrics {
  readonly files: number;
  readonly lines: number;
  readonly byExtension: ReadonlyArray<{
    readonly extension: string;
    readonly files: number;
    readonly lines: number;
  }>;
}

export interface GitMetrics {
  readonly commits: number;
  readonly firstCommit: string;
  readonly lastCommit: string;
  readonly authors: ReadonlyArray<{
    readonly email: string;
    readonly commits: number;
  }>;
}

export interface TestMetrics {
  readonly files: number;
  readonly cases: number;
}

export interface SchemaMetrics {
  readonly tables: number;
  readonly migrations: number;
  readonly d1Migrations: number;
}

export interface ApiMetrics {
  readonly routeFiles: number;
  readonly endpoints: number;
}

export interface Metrics {
  readonly loc: LocMetrics;
  readonly git: GitMetrics;
  readonly tests: TestMetrics;
  readonly schema: SchemaMetrics;
  readonly api: ApiMetrics;
  readonly coverageThreshold: number;
  readonly coveredWorkspaces: number;
}

/** Split command output into non-empty trimmed lines. */
export function toLines(output: string): string[] {
  return output
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

/** List tracked files matching the given glob patterns. */
function listTracked(deps: MetricsDeps, patterns: readonly string[]): string[] {
  return toLines(deps.run("git", ["ls-files", "--", ...patterns]));
}

/** Count newline-delimited lines in a file, counting a trailing partial line. */
export function countLines(content: string): number {
  if (content.length === 0) return 0;
  const newlines = content.split("\n").length - 1;
  return content.endsWith("\n") ? newlines : newlines + 1;
}

/**
 * Lines of code across tracked source files. Uses `git ls-files` rather than a
 * filesystem walk so the count respects .gitignore and matches what is actually
 * published.
 */
export function collectLoc(deps: MetricsDeps): LocMetrics {
  const byExtension = SOURCE_EXTENSIONS.map((extension) => {
    const paths = listTracked(deps, [`*.${extension}`]);
    let lines = 0;
    for (const filePath of paths) {
      const content = deps.readFile(filePath);
      if (content !== null) lines += countLines(content);
    }
    return { extension, files: paths.length, lines };
  });

  return {
    files: byExtension.reduce((sum, entry) => sum + entry.files, 0),
    lines: byExtension.reduce((sum, entry) => sum + entry.lines, 0),
    byExtension,
  };
}

/** Parse `git shortlog -sne` output into per-email commit counts. */
export function parseShortlog(
  output: string,
): Array<{ email: string; commits: number }> {
  const totals = new Map<string, number>();
  for (const line of toLines(output)) {
    const match = /^(\d+)\s+.*<([^>]+)>$/.exec(line);
    if (!match) continue;
    // Both groups are guaranteed present when the regex matches; String()
    // narrows the indexed-access type without introducing a dead branch.
    const commits = Number(match[1]);
    const email = String(match[2]);
    totals.set(email, (totals.get(email) ?? 0) + commits);
  }
  return [...totals.entries()]
    .map(([email, commits]) => ({ email, commits }))
    .sort((a, b) => b.commits - a.commits);
}

/**
 * History recorded by an export rather than computed from the repository it
 * sits in. Written only into single-commit snapshots — see `parseSourceHistory`.
 */
export const SOURCE_HISTORY_PATH = "docs/source-history.json";

/**
 * Reads history recorded by a snapshot export, or null if there is none.
 *
 * A single-commit snapshot has no history to measure, so computing from its own
 * git would report one commit authored today and silently contradict the README
 * it ships with. When an export records the source repository's figures here,
 * they are used verbatim.
 *
 * Anything malformed falls back to live git rather than throwing: a corrupt
 * provenance file should not break `verify` for someone who just cloned the
 * repository, and the git-derived answer is always defensible.
 */
export function parseSourceHistory(raw: string | null): GitMetrics | null {
  if (raw === null) return null;

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  if (typeof parsed !== "object" || parsed === null) return null;
  const record = parsed as Record<string, unknown>;
  const { commits, firstCommit, lastCommit, authors } = record;

  if (
    typeof commits !== "number" ||
    typeof firstCommit !== "string" ||
    typeof lastCommit !== "string" ||
    !Array.isArray(authors)
  ) {
    return null;
  }

  const parsedAuthors = authors.filter(
    (author): author is { email: string; commits: number } =>
      typeof author === "object" &&
      author !== null &&
      typeof (author as Record<string, unknown>).email === "string" &&
      typeof (author as Record<string, unknown>).commits === "number",
  );
  if (parsedAuthors.length !== authors.length) return null;

  return { commits, firstCommit, lastCommit, authors: parsedAuthors };
}

/**
 * Commit history. Authors are normalized by email: this repository has commits
 * under two display names sharing one address plus an automation identity, so a
 * raw identity count would imply a team that never existed. Normalizing by
 * address also makes the figure survive a display-name change, since renaming
 * an account never rewrites the commits it already authored.
 */
export function collectGit(deps: MetricsDeps): GitMetrics {
  const recorded = parseSourceHistory(deps.readFile(SOURCE_HISTORY_PATH));
  if (recorded) return recorded;

  const commits = toLines(deps.run("git", ["rev-list", "--count", "HEAD"]))[0];
  const dates = toLines(
    deps.run("git", ["log", "--format=%ad", "--date=short"]),
  );

  return {
    commits: Number(commits ?? 0),
    firstCommit: dates.at(-1) ?? "",
    lastCommit: dates[0] ?? "",
    authors: parseShortlog(deps.run("git", ["shortlog", "-sne", "HEAD"])),
  };
}

/**
 * Test file and case counts. The case count is a static approximation: it
 * counts `it(` and `test(` call sites and therefore undercounts table-driven
 * suites written with `it.each`. Running vitest to get an exact figure would
 * make this script slow and environment-dependent; the tradeoff is documented
 * in the generated report rather than hidden.
 */
export function collectTests(deps: MetricsDeps): TestMetrics {
  const paths = listTracked(deps, [
    "*.test.ts",
    "*.test.tsx",
    "*.spec.ts",
    "*.spec.tsx",
  ]);

  let cases = 0;
  for (const filePath of paths) {
    const content = deps.readFile(filePath);
    if (content === null) continue;
    cases += content.match(/\b(?:it|test)(?:\.\w+)*\s*\(/g)?.length ?? 0;
  }

  return { files: paths.length, cases };
}

/** Drizzle table and migration counts. */
export function collectSchema(deps: MetricsDeps): SchemaMetrics {
  const schemaFiles = listTracked(deps, ["apps/api/src/db/schema/*.ts"]);
  let tables = 0;
  for (const filePath of schemaFiles) {
    const content = deps.readFile(filePath);
    if (content === null) continue;
    tables += content.match(/=\s*pgTable\(/g)?.length ?? 0;
  }

  return {
    tables,
    migrations: listTracked(deps, ["apps/api/migrations/*.sql"]).length,
    d1Migrations: listTracked(deps, ["apps/api/d1-migrations/*.sql"]).length,
  };
}

/**
 * API surface. The endpoint count comes from Hono's own route table rather than
 * from grepping source: barrel files and routers mounted at two paths make text
 * matching produce anything between 68 and 196 depending on the pattern.
 */
export async function collectApi(deps: MetricsDeps): Promise<ApiMetrics> {
  // A git pathspec `*` already crosses directory boundaries, so this single
  // pattern matches every depth. Barrel files are excluded: they re-export
  // rather than define endpoints.
  const routeFiles = listTracked(deps, ["apps/api/src/routes/*.ts"]).filter(
    (filePath) => !filePath.endsWith("/index.ts"),
  );
  return {
    routeFiles: routeFiles.length,
    endpoints: await deps.countEndpoints(),
  };
}

/**
 * Assert every workspace with a test suite declares the per-file coverage
 * thresholds, and return the threshold value. Throws when a workspace has
 * drifted, which is the point: the README claims this and the claim is checked.
 */
export function collectCoverageThreshold(deps: MetricsDeps): number {
  const expected = 95;
  for (const workspace of COVERED_WORKSPACES) {
    const config = deps.readFile(`${workspace}/vitest.config.ts`);
    if (config === null) {
      throw new Error(`Missing ${workspace}/vitest.config.ts`);
    }
    const normalized = config.replace(/\s+/g, " ");
    if (!normalized.includes("perFile: true")) {
      throw new Error(`${workspace} does not enforce per-file coverage`);
    }
    for (const metric of ["lines", "functions", "branches", "statements"]) {
      if (!normalized.includes(`${metric}: ${expected}`)) {
        throw new Error(
          `${workspace} does not enforce ${metric} coverage at ${expected}%`,
        );
      }
    }
  }
  return expected;
}

/** Gather every metric. */
export async function collectMetrics(deps: MetricsDeps): Promise<Metrics> {
  return {
    loc: collectLoc(deps),
    git: collectGit(deps),
    tests: collectTests(deps),
    schema: collectSchema(deps),
    api: await collectApi(deps),
    coverageThreshold: collectCoverageThreshold(deps),
    coveredWorkspaces: COVERED_WORKSPACES.length,
  };
}

/** Format an integer with thousands separators. */
export function formatNumber(value: number): string {
  return value.toLocaleString("en-US");
}

export const README_START = "<!-- METRICS:START -->";
export const README_END = "<!-- METRICS:END -->";

/** The compact table embedded in README.md. */
export function renderReadmeBlock(metrics: Metrics): string {
  const { loc, git, tests, schema, api } = metrics;
  return [
    README_START,
    "",
    "| | |",
    "| --- | --- |",
    `| Source | ${formatNumber(loc.lines)} lines across ${formatNumber(loc.files)} files |`,
    `| Tests | ${formatNumber(tests.files)} files, ~${formatNumber(tests.cases)} cases |`,
    `| Coverage gate | ${metrics.coverageThreshold}% per file, enforced in ${metrics.coveredWorkspaces} workspaces |`,
    `| Database | ${schema.tables} tables, ${schema.migrations} migrations |`,
    `| API | ${api.endpoints} endpoints across ${api.routeFiles} route files |`,
    `| History | ${formatNumber(git.commits)} commits, ${git.firstCommit} to ${git.lastCommit} |`,
    "",
    README_END,
  ].join("\n");
}

/** The detailed report at portfolio/METRICS.md, including methodology. */
export function renderMetricsDoc(metrics: Metrics): string {
  const { loc, git, tests, schema, api } = metrics;

  const extensionRows = loc.byExtension
    .filter((entry) => entry.files > 0)
    .map(
      (entry) =>
        `| \`.${entry.extension}\` | ${formatNumber(entry.files)} | ${formatNumber(entry.lines)} |`,
    )
    .join("\n");

  const authorRows = git.authors
    .map(
      (author) => `| \`${author.email}\` | ${formatNumber(author.commits)} |`,
    )
    .join("\n");

  return `# Metrics

Generated by \`pnpm run metrics:generate\`. Do not edit by hand: \`pnpm run
metrics:check\` runs in the \`verify\` chain and fails if this file drifts from
what the repository actually contains.

## Source

${formatNumber(loc.lines)} lines across ${formatNumber(loc.files)} tracked files.

| Extension | Files | Lines |
| --- | --- | --- |
${extensionRows}

Counted with \`git ls-files\` rather than a filesystem walk, so the figure
respects \`.gitignore\` and reflects what is actually published. Includes test
files.

## Tests

${formatNumber(tests.files)} test files containing approximately
${formatNumber(tests.cases)} cases.

The case count is a static approximation: it counts \`it(\` and \`test(\` call
sites, so it undercounts table-driven suites written with \`it.each\`. Running
vitest to get an exact number would make this script slow and dependent on a
working environment, which defeats the purpose of a fast reproducible check.

Every workspace with a test suite enforces **${metrics.coverageThreshold}%
coverage per file** on lines, functions, branches, and statements, not a
repository average. \`metrics:check\` asserts this rather than computing it, and
fails if any of the ${metrics.coveredWorkspaces} configs drift.

## Database

${schema.tables} Drizzle tables and ${schema.migrations} SQL migrations.

A further ${schema.d1Migrations} migrations exist for the Cloudflare D1 database
that holds nonce tables. They are counted separately because it is a different
database with an unrelated lifecycle.

## API

${api.endpoints} unique HTTP endpoints across ${api.routeFiles} route files.

The endpoint count comes from Hono's own route table, not from grepping source.
Text matching gives anywhere between 68 and 196 depending on the pattern,
because barrel files and routers mounted at two paths both distort a naive
count. Middleware registrations (\`ALL\`) are excluded; only real method plus
path pairs are counted.

## History

${formatNumber(git.commits)} commits from ${git.firstCommit} to ${git.lastCommit}.

| Author email | Commits |
| --- | --- |
${authorRows}

Normalized by email address. Commits appear under more than one display name
for the same address, and one identity is an automation account rather than a
person.
`;
}

/** Replace the generated block in README.md, leaving the rest untouched. */
export function replaceReadmeBlock(readme: string, block: string): string {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);
  if (start === -1 || end === -1) {
    throw new Error(
      `README.md is missing the ${README_START} / ${README_END} markers`,
    );
  }
  return readme.slice(0, start) + block + readme.slice(end + README_END.length);
}
