/**
 * Turns the manifest written by the capture-*.spec.ts runs into a browsable
 * index at docs/screenshots/README.md.
 *
 *   pnpm run screenshots:index
 *
 * Run after `pnpm --filter @boardstack/app run e2e:capture`.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const archiveRoot = path.join(repoRoot, "docs", "screenshots");
const manifestPath = path.join(archiveRoot, ".manifest.jsonl");
const indexPath = path.join(archiveRoot, "README.md");

interface ManifestEntry {
  file: string;
  surface: string;
  route: string;
  viewport: string;
}

/**
 * The PNGs on disk are the source of truth. The manifest only supplies the
 * route and viewport each was captured at, and the capture specs append to it
 * without resetting — so a spec that ran in an earlier session cannot delete
 * another spec's rows, and a stale row for a deleted file is simply ignored.
 */
function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.isFile() && entry.name.endsWith(".png")) yield full;
  }
}

const metadata = new Map<string, ManifestEntry>();
if (existsSync(manifestPath)) {
  for (const line of readFileSync(manifestPath, "utf8").split(/\r?\n/)) {
    if (line.trim().length === 0) continue;
    const entry = JSON.parse(line) as ManifestEntry;
    metadata.set(entry.file, entry);
  }
}

const deduped = new Map<string, ManifestEntry>();
for (const absolute of walk(archiveRoot)) {
  const file = path.relative(archiveRoot, absolute).split(path.sep).join("/");
  const known = metadata.get(file);
  deduped.set(
    file,
    known ?? {
      file,
      surface: path.dirname(file),
      route: "n/a",
      viewport: "n/a",
    },
  );
}

if (deduped.size === 0) {
  console.error(
    `No screenshots under ${path.relative(repoRoot, archiveRoot)}.\n` +
      "Run the capture specs first — see docs/local-development.md.",
  );
  process.exit(1);
}

const bySurface = new Map<string, ManifestEntry[]>();
for (const entry of deduped.values()) {
  const list = bySurface.get(entry.surface) ?? [];
  list.push(entry);
  bySurface.set(entry.surface, list);
}

const SURFACE_NOTES: Record<string, string> = {
  "app-states": "Dialogs, validation, and zero-data screens.",
  flows: "Unauthenticated screens and the owner portal.",
};

function describeSurface(surface: string): string {
  if (SURFACE_NOTES[surface]) return SURFACE_NOTES[surface];
  if (surface.startsWith("app/")) {
    return `Dashboard at ${surface.slice(4)}px wide.`;
  }
  if (surface.startsWith("web/")) {
    return `Marketing site at ${surface.slice(4)}px wide.`;
  }
  return "";
}

const sections = [...bySurface.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([surface, list]) => {
    const rows = list
      .sort((a, b) => a.file.localeCompare(b.file))
      .map(
        (entry) =>
          `| [\`${path.basename(entry.file)}\`](${entry.file}) | \`${entry.route}\` | ${entry.viewport} |`,
      )
      .join("\n");

    const note = describeSurface(surface);
    return [
      `## ${surface}`,
      "",
      ...(note ? [note, ""] : []),
      "| Screenshot | Route | Viewport |",
      "| --- | --- | --- |",
      rows,
      "",
    ].join("\n");
  });

const doc = `# Screenshots

${deduped.size} captures from a locally seeded instance. Every account, name,
address, and dollar amount is fabricated by
[\`apps/api/scripts/seed-demo.ts\`](../../apps/api/scripts/seed-demo.ts): none of
it came from a real community.

Generated by \`pnpm run screenshots:index\` from the manifest the capture specs
write. To regenerate the images, follow
[docs/local-development.md](../local-development.md), then:

\`\`\`bash
pnpm --filter @boardstack/app run e2e:capture
pnpm run screenshots:hero
pnpm run screenshots:optimize
pnpm run screenshots:index
\`\`\`

## Rough edges these captures show

Published as captured, without retouching. Three things a careful reader will
notice, all real:

- **The balance sheet does not balance.** The default chart of accounts seeds
  no equity account, so the "Liabilities & Equity" stat sums liabilities only
  and never ties to Assets. The underlying journal is still balanced: the
  trial balance shows debits equal to credits. Explained in
  [portfolio/ACCOUNTING-ENGINE.md](../../portfolio/ACCOUNTING-ENGINE.md).
- **The violation log prints raw unit IDs.** \`_app.governance.violations.tsx\`
  renders \`unitId\` directly instead of joining to the unit number, so rows read
  \`Unit: demo-unit-15\` rather than \`Unit: 116\`.
- **Settings does not preselect the saved state.** \`app/1440/settings.png\` shows
  "Select a state" even though the community's state is \`CA\` in the database and
  \`/communities/me\` returns it. The community *name* beside it populates from
  the same response. Reproducible across capture runs on a fully rendered page.
  The dashboard reads the same value correctly, so this is isolated to the form.

${sections.join("\n")}`;

// Formatted here so the pre-commit Prettier pass does not immediately rewrite
// what this script just produced, which would leave the file permanently
// one `pnpm run screenshots:index` away from its own output.
const prettierOptions = await resolveConfig(indexPath);
writeFileSync(
  indexPath,
  await format(doc, { ...prettierOptions, filepath: indexPath }),
  "utf8",
);
console.log(
  `Wrote ${path.relative(repoRoot, indexPath)} with ${deduped.size} captures.`,
);
